require('icalofir.plugins')
require('icalofir.settings')
require('icalofir.mappings')
require('icalofir.plugins_settings.nvim_cmp')
require('icalofir.plugins_settings.treesitter')
require('icalofir.plugins_settings.indent_guides')
